// Static EXIF data, generated by publisher.py from ExifTool output.
// Keyed by the original filename (without extension), which appears
// as a substring within the Cloudinary public ID after upload.
//
// Do not hand-edit — re-running the publisher regenerates this
// file completely from publisher_data/exif.json.

const EXIF_DATA = {
  "202108011N1A1495": { camera: "Canon EOS R5", lens: "EF24-70mm f/2.8L II USM", focalLength: "39mm", aperture: "f/2.8", shutterSpeed: "1/250s", iso: "640" },
  "202108011N1A1514": { camera: "Canon EOS R5", lens: "EF24-70mm f/2.8L II USM", focalLength: "39mm", aperture: "f/2.8", shutterSpeed: "1/250s", iso: "640" },
  "202108011N1A1547": { camera: "Canon EOS R5", lens: "EF24-70mm f/2.8L II USM", focalLength: "35mm", aperture: "f/2.8", shutterSpeed: "1/250s", iso: "640" },
  "202108011N1A1595": { camera: "Canon EOS R5", lens: "EF24-70mm f/2.8L II USM", focalLength: "35mm", aperture: "f/2.8", shutterSpeed: "1/250s", iso: "640" },
  "202108011N1A1608": { camera: "Canon EOS R5", lens: "EF24-70mm f/2.8L II USM", focalLength: "35mm", aperture: "f/2.8", shutterSpeed: "1/250s", iso: "640" },
  "202108011N1A1619": { camera: "Canon EOS R5", lens: "EF24-70mm f/2.8L II USM", focalLength: "35mm", aperture: "f/2.8", shutterSpeed: "1/250s", iso: "800" },
  "202108011N1A1632": { camera: "Canon EOS R5", lens: "EF24-70mm f/2.8L II USM", focalLength: "31mm", aperture: "f/2.8", shutterSpeed: "1/250s", iso: "800" },
  "202108011N1A1681": { camera: "Canon EOS R5", lens: "EF24-70mm f/2.8L II USM", focalLength: "33mm", aperture: "f/2.8", shutterSpeed: "1/250s", iso: "640" },
  "202108011N1A1719": { camera: "Canon EOS R5", lens: "EF24-70mm f/2.8L II USM", focalLength: "33mm", aperture: "f/2.8", shutterSpeed: "1/250s", iso: "640" },
  "202108011N1A1758": { camera: "Canon EOS R5", lens: "EF24-70mm f/2.8L II USM", focalLength: "35mm", aperture: "f/2.8", shutterSpeed: "1/250s", iso: "640" },
  "202108011N1A1810": { camera: "Canon EOS R5", lens: "EF24-70mm f/2.8L II USM", focalLength: "35mm", aperture: "f/2.8", shutterSpeed: "1/250s", iso: "640" },
  "202108011N1A1821": { camera: "Canon EOS R5", lens: "EF24-70mm f/2.8L II USM", focalLength: "28mm", aperture: "f/2.8", shutterSpeed: "1/250s", iso: "640" },
  "202108011N1A1872": { camera: "Canon EOS R5", lens: "EF24-70mm f/2.8L II USM", focalLength: "30mm", aperture: "f/2.8", shutterSpeed: "1/250s", iso: "640" },
  "202108011N1A1882": { camera: "Canon EOS R5", lens: "EF24-70mm f/2.8L II USM", focalLength: "28mm", aperture: "f/2.8", shutterSpeed: "1/250s", iso: "640" },
  "202108011N1A1926": { camera: "Canon EOS R5", lens: "EF24-70mm f/2.8L II USM", focalLength: "44mm", aperture: "f/2.8", shutterSpeed: "1/250s", iso: "640" },
  "202108011N1A1946": { camera: "Canon EOS R5", lens: "EF24-70mm f/2.8L II USM", focalLength: "38mm", aperture: "f/2.8", shutterSpeed: "1/250s", iso: "640" },
  "202108011N1A1959": { camera: "Canon EOS R5", lens: "EF24-70mm f/2.8L II USM", focalLength: "33mm", aperture: "f/2.8", shutterSpeed: "1/250s", iso: "640" },
  "202108011N1A1972": { camera: "Canon EOS R5", lens: "EF24-70mm f/2.8L II USM", focalLength: "33mm", aperture: "f/2.8", shutterSpeed: "1/250s", iso: "640" },
  "202108011N1A1978": { camera: "Canon EOS R5", lens: "EF24-70mm f/2.8L II USM", focalLength: "35mm", aperture: "f/2.8", shutterSpeed: "1/250s", iso: "640" },
  "202108011N1A2028": { camera: "Canon EOS R5", lens: "EF24-70mm f/2.8L II USM", focalLength: "31mm", aperture: "f/2.8", shutterSpeed: "1/250s", iso: "640" },
};
